// Generates src/icons.ts from Simple Icons (CC0).
// Paths are rescaled from the 24×24 box to integers on a 72×72 box and re-serialized
// as compact relative commands, which roughly halves their size with no visible loss at icon sizes.
//
// Usage: bun scripts/icons.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import svgpath from 'svgpath'
import * as si from 'simple-icons'

// Icons removed from recent Simple Icons releases, extracted from simple-icons@9 (CC0).
const LEGACY = JSON.parse(readFileSync(new URL('./legacy-icons.json', import.meta.url), 'utf8'))

const MAP = {
  x: 'x',
  facebook: 'facebook',
  messenger: 'messenger',
  whatsapp: 'whatsapp',
  telegram: 'telegram',
  linkedin: 'linkedin',
  reddit: 'reddit',
  pinterest: 'pinterest',
  tumblr: 'tumblr',
  bluesky: 'bluesky',
  mastodon: 'mastodon',
  threads: 'threads',
  hackernews: 'ycombinator',
  vk: 'vk',
  ok: 'odnoklassniki',
  weibo: 'sinaweibo',
  qzone: 'qzone',
  douban: 'douban',
  wechat: 'wechat',
  line: 'line',
  kakaotalk: 'kakaotalk',
  naver: 'naver',
  hatena: 'hatenabookmark',
  xing: 'xing',
  snapchat: 'snapchat',
  substack: 'substack',
  flipboard: 'flipboard',
  instapaper: 'instapaper',
  blogger: 'blogger',
  livejournal: 'livejournal',
  teams: 'microsoftteams',
  viber: 'viber',
  buffer: 'buffer',
  classroom: 'googleclassroom',
  gmail: 'gmail',
  outlook: 'microsoftoutlook',
  yahoo: 'yahoo',
}

const num = (n) => {
  let s = String(n)
  if (s.startsWith('0.')) s = s.slice(1)
  else if (s.startsWith('-0.')) s = '-' + s.slice(2)
  return s
}

/** Scale a path from a 24 box to a 72 box, round to integers, serialize compactly. */
export const compact = (d, scale = 3) => {
  const p = svgpath(d).scale(scale).rel().round(0)
  let out = ''
  let prevCmd = ''
  let prevNum = ''
  for (const seg of p.segments) {
    let [cmd, ...args] = seg
    if (cmd === 'l' && args[1] === 0) [cmd, args] = ['h', [args[0]]]
    else if (cmd === 'l' && args[0] === 0) [cmd, args] = ['v', [args[1]]]
    if (cmd === 'l' && args.every((a) => a === 0)) continue
    if (cmd !== prevCmd || /[mz]/i.test(cmd)) {
      out += cmd
      prevNum = ''
    }
    for (const a of args) {
      const s = num(a)
      if (prevNum && !s.startsWith('-') && !(s.startsWith('.') && prevNum.includes('.'))) out += ' '
      out += s
      prevNum = s
    }
    prevCmd = cmd
  }
  return out
}

const shortHex = (hex) => {
  const h = hex.toLowerCase()
  return h[0] === h[1] && h[2] === h[3] && h[4] === h[5] ? h[0] + h[2] + h[4] : h
}

const bySlug = {}
for (const k in si) if (si[k]?.slug) bySlug[si[k].slug] = si[k]

let out = `// Generated by scripts/icons.mjs from Simple Icons (CC0). Do not edit by hand.
// Brand icons are trademarks of their respective owners.
// Paths use a 72×72 box. The comment after each name is the brand color.\n\n`
let total = 0
for (const [id, slug] of Object.entries(MAP)) {
  const icon = bySlug[slug] ?? LEGACY[slug]
  if (!icon) throw new Error('Missing icon ' + slug)
  const path = compact(icon.path)
  total += path.length
  out += `/** ${icon.title ?? slug}, #${shortHex(icon.hex)} */\nexport const ${id}: string = '${path}'\n`
}
writeFileSync(new URL('../src/icons.ts', import.meta.url), out)
console.log(`src/icons.ts: ${Object.keys(MAP).length} icons, ${total} path bytes`)
